use clap::{App, Arg, SubCommand};

pub fn create_app<'a>() -> App<'a, 'a> {
  App::new("zfiles")
    .version("0.1.0")
    .author("Ion Ostafi <ostafi_ion@yahoo.com>")
    .about("Tool for reading passwords from backup file generated by blackberry password app for blackberry OS 10.")
    .subcommand(
      SubCommand::with_name("show")
      .about("View passwords")
      .arg(
        Arg::with_name("names")
        .short("-n")
        .long("--names")
        .help("Print only names")
        .takes_value(false)
      )
      .arg(
        Arg::with_name("passwords")
        .short("-p")
        .long("--passwords")
        .help("Print passwords only")
        .takes_value(false)
      )
    )
}
