extern crate clap;
use clap::{App, Arg, SubCommand};

pub fn create_app<'a>() -> App<'a, 'a> {
  App::new("zfiles")
    .version("0.1.0")
    .author("Ion Ostafi <ostafi_ion@yahoo.com>")
    .about("Tool for reading passwords from backup file generated by blackberry password app for blackberry OS 10.")
    .subcommand(
      SubCommand::with_name("show")
      .about("View passwords")
      .arg(
        Arg::with_name("names")
        .short("-n")
        .long("--names")
        .help("Print only names")
        .takes_value(false)
      )
      .arg(
        Arg::with_name("passwords")
        .short("-p")
        .long("--passwords")
        .help("Print passwords only")
        .takes_value(false)
      )
    )
    .subcommand(
      SubCommand::with_name("add")
      .about("Add new password to the registry")
      .arg(
        Arg::with_name("name")
        .short("-n")
        .long("--name")
        .help("Name of the new record")
        .takes_value(true)
      )
      .arg(
        Arg::with_name("password")
        .short("-p")
        .long("--password")
        .help("Password of the new record")
        .takes_value(true)
      )
    )
}

#[cfg(test)]
mod tests {
    #[test]
    fn test_App() {
        assert_eq!(2 + 2, 4);
    }
}
